//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int idUsuario { get; set; }
        public long Persona_idPersona { get; set; }
        public string Nombre_de_Usuario { get; set; }
        public string Contraseña { get; set; }
        public bool Estado { get; set; }
    }
}
