//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBases2018.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"""metadata=res://*/ProyectoBases2018.csdl|res://*/ProyectoBases2018.ssdl|res://*/ProyectoBases2018.msl;provider=MySql.Data.MySqlClient;provider connection string=&quot;server=localhost;user id=ghidalgo;password=Nevermind1992*;database=dbuasj;persistsecurityinfo=True&quot;""")]
        public string Conexion {
            get {
                return ((string)(this["Conexion"]));
            }
            set {
                this["Conexion"] = value;
            }
        }
    }
}
